document.addEventListener('DOMContentLoaded',function(){
  const style=document.createElement('style');style.textContent='#homeLanding{display:none;margin-bottom:1rem}.home-hero{position:relative;overflow:hidden;border-radius:1rem;margin-bottom:1rem;background:#171a20;min-height:190px}.home-hero img{display:block;width:100%;height:clamp(190px,35vw,330px);object-fit:cover;object-position:center 45%}.home-hero>div{position:absolute;inset:auto 0 0;padding:1.2rem 1rem .9rem;color:#fff;background:linear-gradient(transparent,rgba(0,0,0,.8))}.home-hero h2{font-size:clamp(1.15rem,3vw,1.7rem);font-weight:800;margin:0 0 .25rem}.home-hero p{margin:0;font-size:.9rem}.home-choice-grid{display:grid;grid-template-columns:1fr;gap:.75rem}.home-choice-grid button{display:flex;align-items:center;gap:.8rem;width:100%;padding:1rem;border:1px solid var(--bs-border-color);border-radius:.9rem;background:var(--bs-body-bg);color:var(--bs-body-color);text-align:right;font:inherit;cursor:pointer}.home-choice-grid button>i:first-child{display:flex;align-items:center;justify-content:center;flex:0 0 3rem;height:3rem;border-radius:.8rem;background:var(--bs-secondary-bg);color:var(--bs-primary);font-size:1.35rem}.home-choice-grid button>span{flex:1;min-width:0}.home-choice-grid strong,.home-choice-grid small{display:block}.home-choice-grid small{margin-top:.2rem;color:var(--bs-secondary-color)}@media(min-width:700px){.home-choice-grid{grid-template-columns:repeat(3,minmax(0,1fr))}.home-choice-grid button{align-items:flex-start;flex-direction:column;min-height:145px}}';document.head.appendChild(style);\n  const main=document.querySelector('.app-content .container-fluid');
  if(!main||document.getElementById('homeLanding'))return;
  const landing=document.createElement('section');
  landing.id='homeLanding';
  landing.innerHTML='<div class="home-hero"><img src="./docs/images/pages/page-0001.png" alt="موتور بنلی"><div><h2>راهنمای Benelli TNT 249</h2><p>دفترچه تعمیراتی دیجیتال</p></div></div><div class="home-choice-grid"><button type="button" data-home-choice="fa"><i class="bi bi-translate"></i><span><strong>راهنمای فارسی</strong><small>مطالب ترجمه‌شده دفترچه</small></span></button><button type="button" data-home-choice="en"><i class="bi bi-book"></i><span><strong>راهنمای انگلیسی</strong><small>صفحات اصلی دفترچه</small></span></button><button type="button" data-home-choice="repair"><i class="bi bi-wrench-adjustable"></i><span><strong>راهنمای بخش تعمیرات</strong><small>موضوعات تعمیراتی</small></span></button></div>';
  const nav=main.querySelector('.search-navigation');
  main.insertBefore(landing,nav||main.firstChild);
  function home(){landing.style.display='block';if(nav)nav.style.display='none';const card=nav&&nav.nextElementSibling;if(card)card.style.display='none';['#status','#results'].forEach(s=>{const x=main.querySelector(s);if(x)x.style.display='none'});document.querySelector('#detail')?.classList.add('hidden');document.querySelector('#pdfViewer')?.classList.add('hidden');if(typeof setPageHeader==='function')setPageHeader('راهنمای تعمیر Benelli TNT 249','خانه');window.scrollTo({top:0,behavior:'smooth'});}
  function leave(){landing.style.display='none';if(nav)nav.style.display='';const card=nav&&nav.nextElementSibling;if(card)card.style.display='';['#status','#results'].forEach(s=>{const x=main.querySelector(s);if(x)x.style.display=''});}
  document.addEventListener('click',function(e){const h=e.target.closest('#homeHeader,#brandHome,[data-home],.filters-btn[data-filter="home"]');if(h){e.preventDefault();e.stopImmediatePropagation();history.pushState({tnt249:true,view:'home',mode:'home'},'',location.href);home();return;}const c=e.target.closest('[data-home-choice]');if(c){leave();if(c.dataset.homeChoice==='repair')document.querySelector('.filters button[data-filter="repair"]')?.click();else document.querySelector('.manual-lang-btn[data-manual-lang="'+c.dataset.homeChoice+'"]')?.click();return;}if(e.target.closest('.manual-lang-btn,.filters button:not([data-filter="home"]),[data-topic],[data-page],[data-pdf],[data-manual-page]'))leave();},true);
  window.addEventListener('popstate',function(e){if(e.state?.view==='home'&&(e.state.mode||'home')==='home')home();else leave()});
  window.addEventListener('load',function(){if(history.state?.view==='home'&&(history.state.mode||'home')==='home')home()});
});